spring.application.name=menu
spring.datasource.url=jdbc:mysql://localhost:3306/coffeeshop_db
spring.datasource.username=root
spring.datasource.password=Anhpq20051304@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

coffee.shop=DOPE Coffee
address.shop=Lê Đức Thọ, Phường An Hội Đông, TP. Hồ Chí Minh