spring.application.name=management
spring.datasource.url=jdbc:mysql://localhost:3306/project_db
spring.datasource.username=root
spring.datasource.password=Anhpq20051304@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

college.name=Bach Viet Polytechnic
graduation.year=2026